### ISSUE TITLE
[BOSS] Big_chunky

### ISSUE THREAD

**Issue by zelytra** [HisteriaMC/histeria-wiki#19]

**Comment by Tonmou8128** [comment]
Big chunky n'existe pas, on peut fermer l'issue ?

**Comment by Tonmou8128** [comment]
![Screenshot_2023-12-26-18-02-05-37_572064f74bd5f9fa804b05334aa4f912~2](https://github.com/HisteriaMC/histeria-wiki/assets/149319443/1cab3bb7-8059-4bed-ad6f-b98af9560186)
