### ISSUE TITLE
[TOOL] Calice de Dyonisos

### ISSUE THREAD

**Issue by zelytra** [HisteriaMC/histeria-wiki#206]
A rediger

**Comment by zelytra** [comment]
Une PR est lié a une de tes branches. Il te suffit de creer une autre branche et de creer une nouvelle PR. Ce qui te permet de traiter plusieurs PR/taches en meme temp. Tu peut changer de branche comme bon te semble

**Comment by Tonmou8128** [comment]
Super, alors je m'en occuperai bientôt
