### ISSUE TITLE
[ITEMS] Totem en histerite 

### ISSUE THREAD

**Issue by Tonmou8128** [HisteriaMC/histeria-wiki#212]
Je vais le rédiger dès que j'ai des infos

**Comment by SwouitAzia** [comment]
![image](https://github.com/HisteriaMC/histeria-wiki/assets/126331308/ac2a3709-8985-45de-8964-627e95986f79)
tu diras merci à TTV, seul mec qui a un totem en hst du serveur (j'ai l'impression).

**Comment by Tonmou8128** [comment]
> ![image](https://private-user-images.githubusercontent.com/126331308/291641813-ac2a3709-8985-45de-8964-627e95986f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDE3MjQsIm5iZiI6MTcwMzAwMTQyNCwicGF0aCI6Ii8xMjYzMzEzMDgvMjkxNjQxODEzLWFjMmEzNzA5LTg5ODUtNDVkZS04OTY0LTYyN2U5NTk4NmY3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNTU3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWZhOTQ0MWI1NzM4ODFlZGZjYjRlNDkxZTY3ZTEwODg2ODIwMDlhZmM4Y2IxOTFmMDcwMmRlN2M0ZWUyYTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LyVg2KYItGj3ClHZchpxUMXn2amSVHE9dNNYAtSJJvo) tu diras merci à TTV, seul mec qui a un totem en hst du serveur (j'ai l'impression).

Oh super 👌
