### ISSUE TITLE
Punching-ball

### ISSUE THREAD

**Issue by Zirowz** [HisteriaMC/histeria-wiki#226]
Indiquer que le punching-ball est récupérable avec une hache en bois

**Comment by SwouitAzia** [comment]
je le mets sur ma PR.

**Comment by SwouitAzia** [comment]
fait (vous pouvez close)

**Comment by zelytra** [comment]
@SwouitAzia Il faut que tu TAG tes mr avec des # en mettant par exemple #226 je ping cette issue. Donc dans la MR concerner tu me peut ecrire dans la description `Close #226` pour que quand la MR qui fait referance a l'issue est merge, alors elle close toute seul l'issue. De meme, ne fais pas de message "Je prend la tache" ca ne sert a rien. Juste ouvre la MR et ping l'issue lier a la MR

> fait (vous pouvez close)

**Comment by zelytra** [comment]
Donc si la tache est faite il y a un probleme. Merci d'aller dans la MR qui concerne cette issue et de la ping.

**Comment by SwouitAzia** [comment]
j'ai pas trop compris ou je devais ping l'issue #226 , la PR n'a pas de description c'est le 1 er commentaire ?).

**Comment by SwouitAzia** [comment]
et c'est quoi "MR" ?

**Comment by zelytra** [comment]
MR = PR et si la PR a bien des description, mais ca marche aussi dan des commentaires
