### ISSUE TITLE
Coffre d'arène 

### ISSUE THREAD

**Issue by Tonmou8128** [HisteriaMC/histeria-wiki#232]
Il y a une erreur de syntaxe markdown à quelque part dans la page

![Screenshot_2023-12-21-14-36-37-59_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/HisteriaMC/histeria-wiki/assets/149319443/2ea43644-e3f8-428f-a22d-3e9f43104a7b)

![Screenshot_2023-12-21-14-36-56-34_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/HisteriaMC/histeria-wiki/assets/149319443/28d3f20e-5bc4-44cc-a877-bcbeed53a210)

**Comment by SwouitAzia** [comment]
pomme hist ?

**Comment by Tonmou8128** [comment]
> pomme hist ?

Je crois bien que je me suis trompé, merci
C'est 3 pommes hist et 20 pommes en or si je me trompe plus

**Comment by Tonmou8128** [comment]
Mais ça ne résout pas le problème flagrant sur le site

**Comment by SwouitAzia** [comment]
oui faut juste retirer un dièse, et pour l'icône c'est à mettre tout en haut sur le fichier.md, genre %%icon=(lien)%%

**Comment by Tonmou8128** [comment]
> oui faut juste retirer un dièse, et pour l'icône c'est à mettre tout en haut sur le fichier.md, genre %%icon=(lien)%%

Pour l'icône le lien est bon pourtant, et le dièse je comprends pas lequel retirer

**Comment by Tonmou8128** [comment]
> Pour l'icône le lien est bon pourtant, et le dièse je comprends pas lequel retirer

En mode preview c'est bon et le code même a l'air bon, mais sur le site non

**Comment by SwouitAzia** [comment]
oublie pour le dièse j'ai rien dit

**Comment by zelytra** [comment]
https://www.markdownguide.org/basic-syntax/#horizontal-rule-best-practices

**Comment by Tonmou8128** [comment]
> https://www.markdownguide.org/basic-syntax/#horizontal-rule-best-practices

Merci, j'ai donc mis un espace avant et après.
J'espère que ça fonctionnera
