### ISSUE TITLE
Images facs / autre

### ISSUE THREAD

**Issue by SwouitAzia** [HisteriaMC/histeria-wiki#237]
Desc. qui sera éditée au fur et à mesure.

- [ ] Fac1
- [ ] 2
- [ ] 3
- [ ] Minage
- [ ] Lobby
- [x] Olympus
- [x] Elysian gardens
- [x] Hell
- [x] Colisseum
- [ ] sorties v6 5
- [x] Atlantis
- [ ] jump v6 5

Screens à prendre sous RTX + trouver moyen de les agrandir sur le wiki.

**Comment by Tonmou8128** [comment]
Quand j'aurai les screens des arènes de boss, je m'en occuperai avec le fonctionnement des boss

**Comment by Tonmou8128** [comment]
*Nextag s'en charge
