### ISSUE TITLE
Réorganisation de l'ordre des pages

### ISSUE THREAD

**Issue by Tonmou8128** [HisteriaMC/histeria-wiki#239]
Avec les nouvelles pages, et même comme ça, une réorganisation serait mieux.
Je m'en occuperai bientôt

**Comment by Tonmou8128** [comment]
Exemple les bâtons seraient mieux les uns à cotés des autres, items de boss pareils, obsidiennes moddés aussi ect...

**Comment by Tonmou8128** [comment]
> avant de réorganiser les pages je propose de revoir l'arborescence du wiki. Objets est blindé de chez blindé on pourrait déjà faire ds sous-dossiers pour les clés et pour les matériaux. ça ferait déjà une quinzaine de pages en moins, une autre avec les utilitaires ou jsp..

Mon avis est que objet donne l'air d'être blindé vu que rien ne va ensemble, si c'est réorganisé ça devrait aller mieux
Après revoir comme tu proposes reste une idée à étudier qui pourrait aussi être utile

**Comment by dadodasyra** [comment]
C'est une huge task à merge après les autres grosses Pr prcq ça va impliquer masse conflicts

**Comment by dadodasyra** [comment]
mais vous pouvez déjà en discuter ici

**Comment by dadodasyra** [comment]
@zelytra possibilité de sous dossier ou pas ? je me souviens plus

**Comment by Tonmou8128** [comment]
> C'est une huge task à merge après les autres grosses Pr prcq ça va impliquer masse conflicts

D'acc

**Comment by zelytra** [comment]
> @zelytra possibilité de sous dossier ou pas ? je me souviens plus

Pour commencer pas possible, ensuite même si possible je refuserais, car pas ERGO. Faite plus de dossier, faut pas que le wiki se retrouve être un explorateur de fichier windows.

Je vous conseille plutot de bien découpé en dossier et de bien gérer l'ordre d'affichage pour rendre le wiki plus claire

**Comment by Tonmou8128** [comment]
Je fais une proposition de départ :

- armures c'est bon
- boss pareil
- commande je vois pas de changements potentiels
- développeur c'est bon
- enchants aussi
- outils pareil

- mondes : coffre d'arène en dernier ?
- - objets : j'aime bien l'idée de séparer l'hist de la noc et des objets, les clés aussi séparés, avec le dossier reward ?
- blocs : les 2 minerais ensemble, les 2 obsi aussi, puis lucky bloc, terre fertile, cave bloc, commode, ascenseur, spike et enfin enclume, les 2 blocs de noc et hist chacun avec leurs matériaux
