### ISSUE TITLE
Dossier rewards

### ISSUE THREAD

**Issue by Tonmou8128** [HisteriaMC/histeria-wiki#252]
Si les métiers vont dans le dossier métiers, il reste ici que le calendrier et les kits, ça fait peu
Soit on les mets dans un autre dossier, soit on ramène des choses dans le dossier rewards ( je pense aux clés )

**Comment by Tonmou8128** [comment]
Ben pour faire une page dessus

**Comment by Tonmou8128** [comment]
?

**Comment by Tonmou8128** [comment]
shop.histeria.fr ?

**Comment by dadodasyra** [comment]
Non ça peut être utile de les mettre sur le wiki
