### ISSUE TITLE
Changement craft drawer upgrade

### ISSUE THREAD

**Issue by dadodasyra** [HisteriaMC/histeria-wiki#259]
remplacement drawer par barrel
![image](https://github.com/HisteriaMC/histeria-wiki/assets/44753923/78ce5cbd-60cd-4a12-ae6a-466ca5d5495d)
to
![image](https://github.com/HisteriaMC/histeria-wiki/assets/44753923/f3d89a73-c727-4e84-bb35-b915068fe6fc)

**Comment by Tonmou8128** [comment]
@HARYA301 Il faudrait le rendu 3d du barrel
