### ISSUE TITLE
Page AP

### ISSUE THREAD

**Issue by SwouitAzia** [HisteriaMC/histeria-wiki#262]
Descriptif AP, s'inspirer du document https://docs.google.com/document/d/11LQdpAqTxI4gPPpsW-E5tHdlNk3NBZt1pvDmyW6JMUk/edit?pli=1#heading=h.mlxo9e5h85uj mais ne pas y mettre le statut de disponibilité.
PS : nécessite 2 pictures : 
- carte (vue de haut)
- aperçu

**Comment by Tonmou8128** [comment]
Pareil, je fais maintenant la page et tu pourras faire les pictures plus tard
