### ISSUE TITLE
Page MDF

### ISSUE THREAD

**Issue by SwouitAzia** [HisteriaMC/histeria-wiki#263]
Descriptif MDF, s'inspirer du document https://docs.google.com/document/d/11LQdpAqTxI4gPPpsW-E5tHdlNk3NBZt1pvDmyW6JMUk/edit?pli=1#heading=h.mlxo9e5h85uj mais ne pas y mettre le statut de disponibilité.
PS : nécessite 2 pictures : 
- carte (vue de haut)
- aperçu

**Comment by Tonmou8128** [comment]
> pour le moment les pictures sont pas disponibles puisque les builds ne sont pas terminés.

Je peux le faire maintenant, les pictures tu pourras le faire avec #237 ?
