### ISSUE TITLE
[BLOCK] NEON

### ISSUE THREAD

**Issue by SwouitAzia** [HisteriaMC/histeria-wiki#270]

**Comment by Tonmou8128** [comment]
Pourquoi pas faire une icone 3d et animée ?

**Comment by Tonmou8128** [comment]
Dans tous les cas il faudrait une icone 3d @HARYA301

**Comment by HARYA301** [comment]
Je ne suis pas chez ma mère (là où y a ma tour) jusqu’à vendredi prochain
Cela dit, je le ferai à mon retour

**Comment by Tonmou8128** [comment]
Aucun problème
