### ISSUE TITLE
[ITEMS] Seed planter

### ISSUE THREAD

**Issue by zelytra** [HisteriaMC/histeria-wiki#36]

**Comment by Alaonestbien** [comment]
Bonjour est ce que je peux m en occuper svp j ai deja un dossier word fait

**Comment by Alaonestbien** [comment]
[seed planteur.docx](https://github.com/HisteriaMC/histeria-wiki/files/11348476/seed.planteur.docx)

**Comment by dadodasyra** [comment]
> [seed planteur.docx](https://github.com/HisteriaMC/histeria-wiki/files/11348476/seed.planteur.docx)

si tu peux l'envoyer sur un post dans le forum discord ce serait cool, avec le lien vers cette issue au passage. Un staff s'en chargera
